### ISSUE TITLE
La construction des miniatures ne marche pas si le fichier est un lien symbolique

### ISSUE THREAD

**Issue by Riduidel** [sebsauvage/MinigalNano#1]
Mes images sont dans un dossier initial "toto".
Comme mon NAS n'a pas l'extension EXIF, je crée des dossiers automatiquement à partir des métadonnées IPTC pour identifier mes images (pas d'EXIF, mais de l'IPTC, c'est bizarre PHP).
Donc, je me retrouve dans le dossier photos avec des tonnes de sous-dossiers contenant des liens symboliques (créés avec [`symlink`](http://www.php.net/manual/en/function.symlink.php)).
Et quand j'affiche un de ces dossiers dans Minigal, les miniatures ne contiennent que l'image d'un "?", ce qui ne peut signifier qu'une chose : le chargement a échoué.

**Comment by danc** [comment]
Mon dossier photos est aussi un lien symbolique.
J'ai des photos affichées correctement, mais pas toutes les photos du répertoire.
Bizarrement, les droits sur toutes les photos des répertoires sont les mêmes (mais il n'y a parfois qu'une photo prise en compte, alors que le répertoire en contient plus ...)

**Comment by jniggemann** [comment]
Mon dossier photos contient quelques 150 liens symboliques vers d'autres dossiers, mais je n'ai pas remarqué de problème...
@danc Est-ce peut-être le problème décrit par nodiscc?

**Comment by tmos** [comment]
Je ferme puisque non reproduit et non explicité.
