### ISSUE TITLE
MiniGal, by ... ?

### ISSUE THREAD

**Issue by tmos** [sebsauvage/MinigalNano#101]
In few places in the software, there is writter "Minigal, by Sébastien Sauvage". I don't have any problem admiting that MiniGal is what it is thanks to Sebsauvage, but don't you think it would be more correct to write "Minigal, by the community", or "Minigal, by the contributors" ?

May be good to have some feedback on this, I don't want to hurt anyone.

**Comment by jniggemann** [comment]
I share your opinion. IMHO the list of contributors has grown to a point where it would be applicable to change this to read "by the minigal open source project" (or something like that)...

**Comment by tmos** [comment]
We may need the approval of @sebsauvage as this is his name that may be, not removed, but moved into the regular list of contributors.

**Comment by jniggemann** [comment]
>We may need the approval of @sebsauvage 

Obviously

**Comment by sebsauvage** [comment]
I have no problem with that. You can move my name to the regular list of
contributors. 

Le 2015-07-06 12:52, Tom.C. a écrit : 

> We may need the approval of @sebsauvage [1] as this is his name that may be, not removed, but moved into the regular list of contributors. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Sébastien SAUVAGE
sebsauvage at sebsauvage dot net
http://sebsauvage.net [3] 

Links:
------
[1] https://github.com/sebsauvage
[2]
https://github.com/sebsauvage/MinigalNano/issues/101#issuecomment-118809822
[3] http://sebsauvage.net

**Comment by tmos** [comment]
Great, thanks you :)
