### ISSUE TITLE
Add 'GIF' text to thumbnails of .gif images

### ISSUE THREAD

**Issue by nodiscc** [sebsauvage/MinigalNano#113]
MinigalNano does not render animated thumbnails for animated gifs or video. While this is fine for performance reasons the user has to explicitely click a thumbnail to realize that the image is an animated sequence (the thumbnail gives no clue of that information). The thumbnail might also not be relevant to the contents of the sequence (I believe the first frame is used).

I'd like thumbnails of GIF files to have the text "GIF" superimposed in the lower right corner. Maybe using https://secure.php.net/manual/en/function.imagefttext.php

**Comment by tmos** [comment]
Hi,
I think it's a great idea !
But I would be implement it template side, in full CSS or maybe with a just a small amout of php (like a variable for image type).
It would avoid to get a new dependency server side, and will be much more friendly for a neat result :)

Obviously, it will be graphicaly oriented to suit the main theme, but if it is just CSS, i'm sure you will be able to adapt it (and I can give help if you need some).

I'll add it in the hole new refactor branch if you don't mind.

Tom

**Comment by nodiscc** [comment]
`php5-gd` is already used server side (https://secure.php.net/manual/en/function.imagefttext.php is a function of gd), but I guess it can also be done in CSS, which I agree is better.

> I'll add it in the hole new refactor branch if you don't mind.

[Cool](https://github.com/sebsauvage/MinigalNano/compare/refactor)

**Comment by nodiscc** [comment]
Unmaintained project
