### ISSUE TITLE
Doesn't generate thumbnails on my new Yunohost 12 install.

### ISSUE THREAD

**Issue by blogdemoi** [sebsauvage/MinigalNano#138]
Hi,

I was very happy with MinigalNano on my previous Yunohost install, but now, with my new install of Yunohost 12 it doesn't generate thumbnails anymore...

I just put all the files in a "my_webapp" app on YH https://github.com/YunoHost-Apps/my_webapp_ynh but thumbnails aren't generated anymore. I tried with "PHP-FPM version can also be selected among (none), 7.4, 8.0, 8.1, 8.2 and 8.3" but no success.

Thank you for any suggestions as I like Minigal Nano and can't find such a simple app.

**Comment by Knah-Tsaeb** [comment]
Hi,
I don't know and use Yunohost.
Can you check if http://your-domain.tld/system_check.php

Possible issue is php-gd is not install.

**Comment by blogdemoi** [comment]
> Hi, I don't know and use Yunohost. Can you check if http://your-domain.tld/system_check.php
> 
> Possible issue is php-gd is not install.

It only returns my Yunohost login web page https://arnauld.org/system_check.php

**Comment by Knah-Tsaeb** [comment]
And after login in ?

**Comment by blogdemoi** [comment]
> And after login in ?

The same, I then have my logged in page where I see my installed apps in Yunohost. 
Do you think it is possible to generate thumbnails on my computer and upload them in the thumbs folder? I tried for an image but the thumbnail didn't show in my photo gallery.

**Comment by Knah-Tsaeb** [comment]
Humm, probably, but can we try to continue to find a solution ?

The url of MinigalNano is https://arnauld.org, right ?
If not try https://url-of-minigal.nano/system_check.php

We need to determinate if php-gd is installed and active.

**Comment by blogdemoi** [comment]
Thank you, here is the result : https://arnauld.org/gallerie/system_check.php

My gallery is at https://arnauld.org/gallerie/ , most of the thumbnails are ok because before upgrading my Yunohost install I just downloaded the whole MinigalNano folder and reuploaded it in my new install. But when I add new pictures, it doesn't generate thumbnails anymore.

Thumbnails not working are in https://arnauld.org/gallerie/?dir=Photos+de+tous+les+jours , where I add daily pictures.

**Comment by blogdemoi** [comment]
So you were right, it seems it is related to "GD image manipulation library". What should I install on Debian 12 (Yunohost server is installed on it) ?

**Comment by Knah-Tsaeb** [comment]
Nice, we catch it !

```shell
sudo apt-get update
sudo apt-get install php-gd
```
And restart php-fpm.

**Comment by blogdemoi** [comment]
Thank you, it worked: https://arnauld.org/gallerie/system_check.php

Thumbnails are generated!

However I had to switch to PHP version 8.3 in the configuration of the "My Webapp" app (app installed in the Yunohost server and in which I can deploy static files).

In this app I can choose different PHP versions, 7.4, 8.0, 8.1, 8.2, 8.3. I used 7.4 first because it was the only one which allows the "ALL" view of my MinigalNano images. If I choose another one the "ALL" functionality doesn't work:

![2024-12-12_14-55](https://github.com/user-attachments/assets/bfa8bd9f-c4e2-41a6-9633-cf847ff25d86)

The best for me would be to install a php-gd version compatible with PHP 7.4 , but maybe it can lead to problems for my server...

**Comment by Knah-Tsaeb** [comment]
MinigalNano is old, not sure it's work with recent PHP version.

For problem with "all", please open new ticket and close this ticket.

**Comment by blogdemoi** [comment]
Merci for your help.

**Comment by seboss666** [comment]
If I'm correct, php-gd package is from Debian repositories, so for the php version debian comes with. To provide php selection, Yunohost also uses Sury repositories, so if you want to switch to unsupported version of php, you need to search and install the target gd module version, like :
```bash
apt install php7.4-php-gd
```
I don't see minigal in the app repository of Yunohost, so I bet it's a 'dead' body you may find harder and harder to maintain over time :/

**Comment by blogdemoi** [comment]
Thank you, that solved my problem. In the "my_webapp" app on YH https://github.com/YunoHost-Apps/my_webapp_ynh I selected PHP version 7.4 then installed php7.4-gd with `sudo apt-get install php7.4-gd` and now the "All" view of images is working and thumbnails are generated.

> I don't see minigal in the app repository of Yunohost

Actually I just upload the MiniGalNano files using sftp in a folder of "my_webapp" app on my Yunohost server.
