### ISSUE TITLE
Quelques problèmes avec le flux RSS

### ISSUE THREAD

**Issue by arthurlutz** [sebsauvage/MinigalNano#48]
J'ai une installation minigalnano où j'aimerais intégrer le flux RSS dans un lecteur d'images qui sait lire du mediarss. Ca ne marche pas (mais bon, c'est peut-être un bug de l'application en question), du coup j'ai regardé la validité du flux. 

Selon http://feedvalidator.org/ j'avais une erreur sur un item où une image contient des espaces dans le nom de fichier de la photo. Il faut probablement échapper le nom de fichier. 

Autre remarque : il fait des warning sur "item should contain a guid element" http://feedvalidator.org/docs/warning/MissingGuid.html  et "Missing atom:link with rel="self"" http://feedvalidator.org/docs/warning/MissingAtomSelfLink.html

Autre truc : le mimetype ne semble pas être xml mais "text/html".

**Comment by tmos** [comment]
I fixed the invalid character with a simple str replace. Does it seems okay on your side ?
