### ISSUE TITLE
masquer un dossier de l'indexation

### ISSUE THREAD

**Issue by tmos** [sebsauvage/MinigalNano#53]
Certains utilisateurs ont des scripts d'upload d'images, et il pourrait être pratique de masquer le dossier du dit script.
Créer un tableau d'éléments à vérifier lors de l'indexation du dossier `photo` serait bienvenu.

**Comment by Knah-Tsaeb** [comment]
Je pense que l'on pourrais aller un peu plus loin.
Exemple :
ROOT
    aFolder
        img_1.jpg
        img_2.jpg
Le but de cette issue est que aFolder ne soit pas indexé (ça c'est ok), mais que les images restent accessible (c'est bon pour ça aussi). Pourtant si j'entre l'url du répertoire /?dir=aFolder je peux lister son contenu. Je pense qu'il faudrait ne pas pouvoir afficher ce répertoire et son contenu.
Qu'en pensez vous ?

//// English version ////
I think we can make it better.
Example :
    aFolder
        img_1.jpg
        img_2.jpg
This goal issue is the aFolder not index (ok, that work), but the img is accessible (it's ok too). But if I load the url of dir /?dir=aFolder I can list dir content. I think is better if dir and content can't be show.
What do you think ?
