### ISSUE TITLE
Regression: images are no more ordered alphabetically by filename

### ISSUE THREAD

**Issue by Lucas-C** [sebsauvage/MinigalNano#85]
Can be observed with the latest version here:
https://chezsoi.org/lucas/wwcb/

**Comment by jniggemann** [comment]
I confirm that this is present in latest HEAD.

**Comment by tmos** [comment]
Should this bug stay open ?

**Comment by Lucas-C** [comment]
No, I think it can be closed. I don't have this issue anymore
