### ISSUE TITLE
RFC: change license / dual-license

### ISSUE THREAD

**Issue by jniggemann** [sebsauvage/MinigalNano#96]
### Introduction
At the moment, MinigalNano is licensed under CC-BY-SA. The people at creativecommons.org [strongly discourage](
https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) (their words, not mine) the use of CC-licenses for software (except CC0). The reasons are explained in the link above.

I share their mindset and would like to propose the following:

### Either dual-license MinigalNano
Add another free or open license. Personally, I'd go with a copyleft license like the GPLv2, but the CC-BY-SA license is incompatible with the GPL, so another open license would have to be chosen if dual-licensing.

### OR re-license MinigalNano
Drop CC-BY-SA and relicense under a free or open license, preferably a copyleft one. Although I'm not entirely sure if that's possible, but then again, IANAL.

Feedback is very much welcome.

**Comment by nodiscc** [comment]
you need an agreement from all previous contributors to relicense..

**Comment by jniggemann** [comment]
Well, just because it's a bit of (tedious?) work it doesn't mean it's not worth it, is it?
I'd volunteer to contact all contributors, trying to get their agreement...

**Comment by nodiscc** [comment]
You're right, I think it's worth it. I agree to relicense my contributions to either GNU GPL, MIT or BSD license.

Lists of contributors can be found at https://github.com/sebsauvage/MinigalNano/blob/master/humans.txt and https://github.com/sebsauvage/MinigalNano/graphs/contributors

**Comment by tmos** [comment]
I agree for the AGLP or GPL, but contacting contributors (specialy pre-seb fork) will be hard I think. But it may worth it :)

**Comment by Lucas-C** [comment]
I agree with the AGLP / GPL re-licensing

**Comment by jniggemann** [comment]
@Lucas-C Thank you!

To not bother those subscribed to this issue, I'll track the status on the wiki: https://github.com/sebsauvage/MinigalNano/wiki

**Comment by Aldarone** [comment]
Ok for me :smiley:

**Comment by bitbybit** [comment]
Ofcourse I agree. GPL or AGPL.

**Comment by iGormilhit** [comment]
As my "contribution", without 's', isn't worth mentionning :smile: , I agree, of course.

**Comment by jniggemann** [comment]
So it's been almost 2 weeks that I sent emails to all contributors and most have answered favorably.

Does anyone know if sebsauvage is still active? His last github activity was a year ago and his webpage is hasn't had activity either...

Can anyone get in touch with the others that have not yet answered (sylvhem, Orangina rouge, bifek)?

**Comment by Lucas-C** [comment]
Yes, sebsauvage is still very active as a blogger at least: http://sebsauvage.net/links/
Have you tried contacting him on his email address ?

**Comment by jniggemann** [comment]
I have, but I got no answer...

**Comment by nodiscc** [comment]
The table on this page is out of date @jniggemann I think you could delete it and track the progress on https://github.com/sebsauvage/MinigalNano/wiki. I agree with AGPL, GPL, BSD or MIT (wiki page updated)

**Comment by jniggemann** [comment]
Thank you for pointing this out: I crated the table on this issue first and then created https://github.com/sebsauvage/MinigalNano/wiki, which reports the current state as mentioned in my comment above.

I forgot to remove the table from this issue, but I already tracked your answer in the wiki 2 weeks ago, check the history :-)
https://github.com/sebsauvage/MinigalNano/wiki/Home/_history

**Comment by Sylvhem** [comment]
I perfectly agree that the CC-BY-SA is a really bad choice. So, that's OK for me to change the license for AGPL, GPL or CeCILL.

**Comment by jniggemann** [comment]
@bifek @OranginaRouge @sebsauvage @cyberic99
Can you please get back to us so we know if you're OK with relicensing your work on MinigalNano?

**Comment by bifek** [comment]
OK with relicensing

**Comment by cyberic99** [comment]
OK for me

**Comment by sebsauvage** [comment]
I'm OK with relicensing. 

Le 12 juin 2015 15:01:21 UTC+02:00, Jan <notifications@github.com> a écrit :
>@bifek @OranginaRouge @sebsauvage @cyberic99
>Can you please get back to us so we know if you're OK with relicensing
>your work on MinigalNano?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sebsauvage/MinigalNano/issues/96#issuecomment-111484531

-- 
Sébastien Sauvage 
sebsauvage@sebsauvage.net 
http://sebsauvage.net

**Comment by OranginaRouge** [comment]
I'm OK with relicensing. 
_The circle is now complete._

**Comment by tmos** [comment]
I think we still need the agreement of the original author, don't we ?

Le 15 juin 2015 12:53:28 GMT+01:00, OranginaRouge <notifications@github.com> a écrit :
>I'm OK with relicensing. 
>_The circle is now complete._
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sebsauvage/MinigalNano/issues/96#issuecomment-112031920

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sebsauvage** [comment]
I do think so. 

Le 2015-06-15 13:57, Tom.C. a écrit : 

> I think we still need the agreement of the original author, don't we ?
> 
> Le 15 juin 2015 12:53:28 GMT+01:00, OranginaRouge <notifications@github.com> a écrit :
>>I'm OK with relicensing. 
>>_The circle is now complete._
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/sebsauvage/MinigalNano/issues/96#issuecomment-112031920
> 
> -- 
> Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
 Sébastien SAUVAGE
 sebsauvage at sebsauvage dot net
 http://sebsauvage.net [2] 

Links:
------
[1]
https://github.com/sebsauvage/MinigalNano/issues/96#issuecomment-112033656
[2] http://sebsauvage.net

**Comment by jniggemann** [comment]
Thank you for your support everyone!
Now that we have this sorted, I'll contact Thomas Rybak and see how he reacts to our proposal. I'll keep you updated!

**Comment by jniggemann** [comment]
http://minigal.dk/ doesn't list any email information, but I could trace the guy to http://www.rybakit.dk/kontakt and sent email 3 weeks ago. Sadly, no answer of Thomas Rybak so far.

**Comment by tmos** [comment]
I think this may be our Thomas here : https://dk.linkedin.com/in/thomasrybak
I have a linkedin account, I can contact him and see...

**Comment by tmos** [comment]
Rybak just answered me !
So he agrees on GPL (I guess AGPL can be fine too if we find advantages on this one), but he really wants to keep the "attribution" part, so (I quote) "the code will state I am the original author and link to my website". So if we can find a way to keep the attribution in the code to his original basis, he is okay with GPL relicencing.

I guess we can add in a php comment header all the licencing stuff, with a line about the original work and a mention "do not remove".

:+1:

**Comment by jniggemann** [comment]
This is great news, now _every contributor_ has agreed to relicense! I'm really excited!!
I'll now figure out how to best tackle the whole licensing transition and will post an idea here.
IMHO we should:
* add a php comment header in every file
* have a license.txt with the actual license we'll select
* maybe rename humans.txt to contributors (or something alike)
Another approach would be to merge the list of contributors along with the mention of the original author to our readme file. I'd even prefer that to having a separate file, as we'd have one readme that 'tells the whole story' (i.e. describes "everything you need to know" about MinigalNano)...

**Comment by jniggemann** [comment]
OK, so which license do we choose? Personally, I'd like to go with the AGPL, because it doesn't have the ASP loophole, which is important since MinigalNano is a webapp.

If we come to an agreement, I'd take the next steps and create some PRs:
- including the text of the license
- prepending a useful header in all PHP files
- merge humans.txt into our README (explicitly stating that T. Rybak is the original author).

How do we proceed?

**Comment by nodiscc** [comment]
> you need an agreement from all previous contributors to relicense... I don't think it's going to happen.

And I was wrong. Congrats @jniggemann and everyone.

I'd also prefer AGPL since it's a strong copyleft license. It's the logical choice for a web application if you were considering GPL (which _does_ have the ASP loophole). MIT/BSD licenses are also common but more permissive

A standard header would be `This file is part of MinigalNano: https://github.com/sebsauvage/MinigalNano` but you can also include a short license header. The license itself could be in a LICENSE file at the root of the repo, prepended with a list of contributors (I use `git shortlog -sne` for this). The README needs to mention the license name, Thomas Rybak and point to the license file itself.

I think this can be done in a single PR. Remind to check that the git shortlog also contains contributors mentioned in humans.txt.

**Comment by tmos** [comment]
Well done every body ! Great day for minigal, we are officialy in AGLP !

**Comment by jniggemann** [comment]
Thank you everyone!!!
